#!/usr/bin/env python3
"""Tests for migrate.py. Run: python3 test_migrate.py

Two of these lock out bugs that were actually shipped and then found:

  * `under_tmp` — the /tmp filter was written as a "/tmp/" prefix test, so a cwd of exactly "/tmp"
    slipped through. That is where ~680 throwaway sessions live, and they would have flooded the
    Desktop sidebar. Case 1 below fails on the pre-fix code.
  * `iso_to_epoch_ms` — transcript timestamps are UTC, but the original used `time.mktime`, which
    reads the parsed struct as LOCAL time. Every createdAt was off by the machine's UTC offset.
    The test pins a real transcript timestamp and runs under a deliberately non-UTC timezone, so
    the pre-fix code fails by exactly the offset.
"""
import importlib.util
import io
import json
import os
import subprocess
import sys
import tempfile
import time
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

# Run in a non-UTC zone on purpose: under TZ=UTC the timestamp bug is invisible, because mktime and
# timegm agree. Bern is UTC+2 in July, which is what made the real defect a two-hour skew.
os.environ["TZ"] = "Europe/Zurich"
time.tzset()

HERE = Path(__file__).resolve().parent
SRC = HERE / "migrate.py"
spec = importlib.util.spec_from_file_location("mig", SRC)
mig = importlib.util.module_from_spec(spec)
sys.argv = ["mig"]
spec.loader.exec_module(mig)

n = 0


def ok(msg):
    global n
    n += 1
    print("  ok:", msg)


# 1. REGRESSION: a cwd of exactly "/tmp" must be filtered. Pre-fix this returned False.
cases = [("/tmp", True), ("/tmp/", True), ("/tmp/tmp-abc", True), ("/var/tmp", True),
         ("/var/tmp/x", True), ("/tmpfoo", False), ("/home/user", False),
         ("/media/user/Data Drive/projects/x", False)]  # embedded space on purpose
for cwd, want in cases:
    got = mig.under_tmp(cwd)
    assert got == want, f"under_tmp({cwd!r}) = {got}, wanted {want}"
ok(f"REGRESSION under_tmp: {len(cases)} cases, incl. bare '/tmp' and the '/tmpfoo' near-miss")

# 2. REGRESSION: transcript timestamps are UTC. This is a real value out of a real transcript.
REAL_TS = "2026-07-10T15:00:29.733Z"
EXPECT_MS = 1783695629000  # 2026-07-10 15:00:29 UTC
assert mig.iso_to_epoch_ms(REAL_TS) == EXPECT_MS, mig.iso_to_epoch_ms(REAL_TS)
buggy = int(time.mktime(time.strptime(REAL_TS[:19], "%Y-%m-%dT%H:%M:%S")) * 1000)  # the old code
assert buggy != EXPECT_MS, "test is inert — pick a timezone where mktime and timegm disagree"
assert (EXPECT_MS - buggy) == 2 * 3600 * 1000, f"skew was {(EXPECT_MS - buggy) / 3.6e6}h, wanted 2h"
ok("REGRESSION iso_to_epoch_ms: UTC honoured; the pre-fix mktime path is off by exactly 2h")

# 3. A missing or malformed timestamp yields None so the caller can fall back to file mtime,
#    rather than raising and killing a whole run over one odd record.
for bad in [None, "", "not-a-time", "2026-13-45T99:99:99Z", 12345, "2026-07-10"]:
    assert mig.iso_to_epoch_ms(bad) is None, f"{bad!r} should be None"
ok("iso_to_epoch_ms: missing/short/malformed/non-string all return None, never raise")

# 4. Title selection rejects the wrappers that are not user prose. Using one would title every
#    migrated session with harness boilerplate.
assert mig.is_real_prompt("修复 worknroll")
assert not mig.is_real_prompt("")
assert not mig.is_real_prompt("   ")
assert not mig.is_real_prompt("Caveat: The messages below were generated by the user")
assert not mig.is_real_prompt("<local-command-stdout>x</local-command-stdout>")
assert not mig.is_real_prompt("<command-name>/compact</command-name>")
assert not mig.is_real_prompt("<system-reminder>do a thing</system-reminder>")
assert not mig.is_real_prompt("[Request interrupted by user]")
ok("is_real_prompt: accepts real prose, rejects all 6 wrapper shapes")

# 5. Content is either a bare string or a list of typed blocks; only text blocks matter.
assert mig.text_of("hello") == "hello"
assert mig.text_of([{"type": "text", "text": "a"}, {"type": "tool_use", "id": "x"},
                    {"type": "text", "text": "b"}]) == "a b"
assert mig.text_of(None) == ""
assert mig.text_of([]) == ""
assert mig.text_of([{"type": "image"}]) == ""
ok("text_of: string, mixed block list, and empty/None all flatten safely")

# 6. scan() on a real-shaped transcript: picks up cwd, skips the wrapper message, keeps the prose.
with tempfile.TemporaryDirectory() as td:
    t = Path(td) / "abc.jsonl"
    t.write_text("\n".join(json.dumps(r) for r in [
        {"type": "user", "cwd": "/home/x/proj", "timestamp": REAL_TS,
         "message": {"role": "user", "content": "Caveat: generated by a local command"}},
        {"type": "user", "cwd": "/home/x/proj", "timestamp": "2026-07-10T15:00:31.000Z",
         "message": {"role": "user", "content": [{"type": "text", "text": "  real   prompt  here "}]}},
    ]) + "\n", encoding="utf-8")
    cwd, title, created = mig.scan(t)
    assert cwd == "/home/x/proj", cwd
    assert title == "real prompt here", repr(title)   # wrapper skipped, whitespace collapsed
    assert created == EXPECT_MS, created              # first timestamp wins, in UTC

    # A transcript with no cwd cannot be placed and must be reported as unusable, not guessed at.
    t2 = Path(td) / "def.jsonl"
    t2.write_text(json.dumps({"type": "summary", "summary": "x"}) + "\n", encoding="utf-8")
    assert mig.scan(t2) is None
ok("scan: extracts cwd/title/createdAt, skips wrappers, returns None with no cwd")

# 7. A corrupt registry record must be REPORTED, not silently skipped — a skipped record means its
#    session gets registered a second time and shows up twice in the sidebar.
with tempfile.TemporaryDirectory() as td:
    d = Path(td)
    (d / "local_good.json").write_text(json.dumps({"cliSessionId": "keep-me"}), encoding="utf-8")
    (d / "local_bad.json").write_text("{not json", encoding="utf-8")
    err = io.StringIO()
    with redirect_stderr(err):
        seen = mig.registered_cli_ids(d)
    assert seen == {"keep-me"}, seen
    assert "local_bad.json" in err.getvalue(), err.getvalue()
    assert "registered twice" in err.getvalue()
ok("registered_cli_ids: keeps the good ids and warns loudly about the unreadable one")

# 8. The record shape: filename must equal sessionId, and model/effort stay OUT so a migrated
#    session is not silently re-pointed at a different model than it originally ran on.
sid, rec = mig.build_record("cli-123", "/home/x/proj", "A title", 1000, 2000)
assert sid.startswith("local_") and rec["sessionId"] == sid
assert rec["cliSessionId"] == "cli-123"
assert rec["cwd"] == rec["originCwd"] == "/home/x/proj"
assert rec["createdAt"] == 1000 and rec["lastActivityAt"] == 2000
assert "model" not in rec and "effort" not in rec, "model/effort must stay unset"
assert rec["bridgeSessionIds"] == [] and rec["isArchived"] is False
sid2, _ = mig.build_record("cli-123", "/home/x/proj", "A title", 1000, 2000)
assert sid != sid2, "each record gets a fresh id"
# createdAt falls back to mtime when the transcript had no usable timestamp
_, rec3 = mig.build_record("cli-9", "/p", "t", None, 5000)
assert rec3["createdAt"] == 5000
ok("build_record: id/filename contract, model+effort omitted, mtime fallback for createdAt")

# 9. Dry run is the default and must not create anything.
with tempfile.TemporaryDirectory() as td:
    p = subprocess.run([sys.executable, str(SRC), "--registry", td, "--limit", "1"],
                       capture_output=True, text=True)
    assert p.returncode == 0, p.stderr
    assert "dry run" in p.stdout, p.stdout
    assert list(Path(td).iterdir()) == [], "a dry run wrote files"
ok("CLI: dry-run by default, registry directory left empty")

# 10. A bad --registry is refused up front, not at the first write half way through a run.
p = subprocess.run([sys.executable, str(SRC), "--registry", "/nope/nope/nope"],
                   capture_output=True, text=True)
assert p.returncode != 0 and "not a directory" in p.stderr, (p.returncode, p.stderr)
ok("CLI: a nonexistent --registry exits before scanning, with a named reason")


# 11. --session picks exactly one transcript, and --title relabels it. Without --session a title
#     would be stamped on every row in the batch, so that combination is refused outright.
def run_main(argv, projects_dir):
    """Drive main() against a fake projects tree, capturing stdout."""
    saved_projects, saved_argv = mig.PROJECTS, sys.argv
    out = io.StringIO()
    try:
        mig.PROJECTS = projects_dir
        sys.argv = ["mig"] + argv
        with redirect_stdout(out):
            mig.main()
        return 0, out.getvalue()
    except SystemExit as e:
        return (e.code or 0), out.getvalue()
    finally:
        mig.PROJECTS, sys.argv = saved_projects, saved_argv


with tempfile.TemporaryDirectory() as td:
    root = Path(td)
    projects = root / "projects" / "-home-x-proj"
    projects.mkdir(parents=True)
    reg = root / "reg"
    reg.mkdir()
    # The fake cwd must be a real directory that is NOT under /tmp: a tempdir cwd is correctly
    # filtered by under_tmp, which would make this test look like a --session failure.
    fake_cwd = str(Path.home())
    for sid in ("aaaa-1111", "bbbb-2222"):
        (projects / f"{sid}.jsonl").write_text(json.dumps({
            "type": "user", "cwd": fake_cwd, "timestamp": REAL_TS,
            "message": {"role": "user", "content": f"prompt for {sid}"}}) + "\n", encoding="utf-8")

    code, out = run_main(["--registry", str(reg), "--session", "aaaa-1111",
                          "--title", "杂活 · chores", "--apply"], root / "projects")
    assert code == 0, (code, out)
    recs = [json.loads(p.read_text(encoding="utf-8")) for p in reg.glob("local_*.json")]
    assert len(recs) == 1, f"--session must register exactly one, got {len(recs)}"
    assert recs[0]["cliSessionId"] == "aaaa-1111", recs[0]["cliSessionId"]
    assert recs[0]["title"] == "杂活 · chores", recs[0]["title"]
    assert "filtered out by --session" in out, out

    # An id that matches nothing registers nothing rather than falling back to "everything".
    for p in reg.glob("local_*.json"):
        p.unlink()
    code, out = run_main(["--registry", str(reg), "--session", "no-such-id", "--apply"],
                         root / "projects")
    assert code == 0 and list(reg.glob("local_*.json")) == [], out
    assert "wrote 0 record(s)" in out, out
ok("--session: registers exactly the named id, --title relabels it, unknown id writes nothing")

# 12. --title alone is refused, because it would stamp one label on every row of a batch.
p = subprocess.run([sys.executable, str(SRC), "--title", "x"], capture_output=True, text=True)
assert p.returncode != 0 and "requires --session" in p.stderr, (p.returncode, p.stderr)
ok("--title without --session is refused with a reason, not silently applied to the batch")


# 13. A session the user DELETED in the app must not be resurrected by a re-run. The app records the
#     deletion as a `deleted_<id>` tombstone holding a millisecond timestamp, written for both the
#     sessionId and the cliSessionId. Without this check a batch run would bring back every session
#     the user had cleared out, and they would have to delete them all again.
with tempfile.TemporaryDirectory() as td:
    root = Path(td)
    projects = root / "projects" / "-home-x-proj"
    projects.mkdir(parents=True)
    reg = root / "reg"
    reg.mkdir()
    fake_cwd = str(Path.home())
    for sid in ("live-1", "killed-2"):
        (projects / f"{sid}.jsonl").write_text(json.dumps({
            "type": "user", "cwd": fake_cwd, "timestamp": REAL_TS,
            "message": {"role": "user", "content": f"prompt {sid}"}}) + "\n", encoding="utf-8")
    (reg / "deleted_killed-2").write_text("1784887395565", encoding="utf-8")

    assert mig.tombstoned_ids(reg) == {"killed-2"}, mig.tombstoned_ids(reg)
    code, out = run_main(["--registry", str(reg), "--apply"], root / "projects")
    assert code == 0, out
    ids = {json.loads(p.read_text(encoding="utf-8"))["cliSessionId"]
           for p in reg.glob("local_*.json")}
    assert ids == {"live-1"}, f"a tombstoned session was resurrected: {ids}"
    assert "deleted in the app" in out, out
ok("tombstones: a session deleted in the app is skipped and reported, never resurrected")


# 14. A session running in a CLI right now must be FLAGGED, because opening it in Desktop before
#     the CLI exits puts two appenders on one transcript. This asserts against the real /proc: this
#     very test runs inside a Claude Code session, so its id must be among the live ones.
live = mig.live_session_ids()
here = os.environ.get("CLAUDE_CODE_SESSION_ID")
if here:
    assert here in live, f"the session running this test ({here}) was not detected among {len(live)}"
    ok(f"live_session_ids: detected {len(live)} running session(s) incl. the one running this test")
else:
    # Never let the check quietly pass as a no-op — say plainly that it did not run.
    print("  SKIP: live_session_ids not asserted — CLAUDE_CODE_SESSION_ID is unset here")

# 15. The flag reaches the output: a live session is marked and warned about, a dead one is not.
with tempfile.TemporaryDirectory() as td:
    root = Path(td)
    projects = root / "projects" / "-home-x-proj"
    projects.mkdir(parents=True)
    reg = root / "reg"
    reg.mkdir()
    fake_cwd = str(Path.home())
    dead_id = "definitely-not-a-running-session"
    ids = [dead_id] + ([here] if here else [])
    for sid in ids:
        (projects / f"{sid}.jsonl").write_text(json.dumps({
            "type": "user", "cwd": fake_cwd, "timestamp": REAL_TS,
            "message": {"role": "user", "content": f"prompt {sid}"}}) + "\n", encoding="utf-8")

    err = io.StringIO()
    with redirect_stderr(err):
        code, out = run_main(["--registry", str(reg)], root / "projects")   # dry run
    assert code == 0, out
    if here:
        assert "[RUNNING NOW]" in out, out
        assert "corrupt" in err.getvalue(), err.getvalue()
        assert out.count("[RUNNING NOW]") == 1, "only the live one may be flagged"
    else:
        assert "[RUNNING NOW]" not in out, out
        assert err.getvalue() == "", err.getvalue()
ok("live flag: marks only the running session and warns on stderr about the shared transcript")


# 16. parse_pick turns a --list selection into indices, and refuses anything it cannot resolve —
#     a typo must never silently register the wrong session.
assert mig.parse_pick("1,3,5", 5) == [0, 2, 4]
assert mig.parse_pick("1-4,7", 10) == [0, 1, 2, 3, 6]
assert mig.parse_pick(" 2 , 2 ", 3) == [1], "dedupes and tolerates spaces"
assert mig.parse_pick("3-3", 3) == [2], "a single-element range is fine"
assert mig.parse_pick("1,,,", 5) == [0], "empty tokens from stray commas are unambiguous — tolerate"
for bad in ["6", "0", "3-1", "x", "", "1-", "-2", ",,"]:
    try:
        mig.parse_pick(bad, 5)
        assert False, f"parse_pick({bad!r}) should have raised"
    except ValueError:
        pass
ok("parse_pick: resolves numbers and ranges, rejects out-of-range/reversed/garbage/empty")

# 17. gather_candidates orders newest-conversation-first by createdAt, deterministically, so the
#     numbers --list prints mean the same thing when --pick runs a moment later.
with tempfile.TemporaryDirectory() as td:
    root = Path(td)
    projects = root / "projects" / "-home-x-proj"
    projects.mkdir(parents=True)
    reg = root / "reg"
    reg.mkdir()
    fake_cwd = str(Path.home())
    triples = [("old-1", "2026-07-10T00:00:00.000Z", "the oldest"),
               ("new-2", "2026-07-12T00:00:00.000Z", "the newest"),
               ("mid-3", "2026-07-11T00:00:00.000Z", "the middle")]
    for sid, ts, txt in triples:
        (projects / f"{sid}.jsonl").write_text(json.dumps({
            "type": "user", "cwd": fake_cwd, "timestamp": ts,
            "message": {"role": "user", "content": txt}}) + "\n", encoding="utf-8")
    saved = mig.PROJECTS
    try:
        mig.PROJECTS = root / "projects"
        cands, skipped, _ = mig.gather_candidates(reg)
    finally:
        mig.PROJECTS = saved
    assert [c["cli_id"] for c in cands] == ["new-2", "mid-3", "old-1"], [c["cli_id"] for c in cands]
ok("gather_candidates: newest-first by createdAt, deterministic")

# 18. --list prints a numbered table and writes nothing; --pick writes exactly the chosen rows in
#     that same numbering; the modes that would both print and write are refused.
with tempfile.TemporaryDirectory() as td:
    root = Path(td)
    projects = root / "projects" / "-home-x-proj"
    projects.mkdir(parents=True)
    reg = root / "reg"
    reg.mkdir()
    fake_cwd = str(Path.home())
    for sid, ts, txt in triples:  # reuse: new-2 -> #1, mid-3 -> #2, old-1 -> #3
        (projects / f"{sid}.jsonl").write_text(json.dumps({
            "type": "user", "cwd": fake_cwd, "timestamp": ts,
            "message": {"role": "user", "content": txt}}) + "\n", encoding="utf-8")

    code, out = run_main(["--registry", str(reg), "--list"], root / "projects")
    assert code == 0, out
    assert out.index("the newest") < out.index("the middle") < out.index("the oldest"), out
    assert list(reg.glob("local_*.json")) == [], "--list must not write"

    code, out = run_main(["--registry", str(reg), "--pick", "1,3", "--apply"], root / "projects")
    assert code == 0, out
    ids = {json.loads(p.read_text(encoding="utf-8"))["cliSessionId"]
           for p in reg.glob("local_*.json")}
    assert ids == {"new-2", "old-1"}, f"--pick 1,3 should be newest+oldest, got {ids}"

    # an out-of-range pick registers nothing and says why
    for p in reg.glob("local_*.json"):
        p.unlink()
    code, _ = run_main(["--registry", str(reg), "--pick", "99", "--apply"], root / "projects")
    assert code and list(reg.glob("local_*.json")) == [], "an invalid --pick must write nothing"

    # incompatible mode combinations are refused, not silently reconciled
    assert run_main(["--registry", str(reg), "--list", "--apply"], root / "projects")[0]
    assert run_main(["--registry", str(reg), "--pick", "1", "--session", "x"], root / "projects")[0]
ok("--list/--pick: list is read-only and numbered; pick writes those rows; bad combos refused")

print(f"\nmigrate.py: all {n} tests PASS")
